# .github/workflows/example.yml
name: Vault Workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://production.vault.11eb56d6-0f95-3a99-a33c-0242ac110007.aws.hashicorp.cloud:8200
          namespace: admin
          method: jwt
          role: gha-vault-jwt
          path: gha
          #jwtGithubAudience: ${{ env.GITHUB_ACTION_REPOSITORY }}
          secrets: secrets/data/gha test | VAULT_SECRET

      - name: Print Secret
        run: echo $"{{ steps.secrets.outputs.VAULT_SECRET }}"