# .github/workflows/example.yml
name: Vault Workflow
on:
  push:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve token
        run: |
          VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r .value)
          echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV
      - name: Print token
        run: echo ${{ env.VAULT_JWT }}
      - name: Retrieve Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: "${{ secrets.VAULT_ADDR }}"
          namespace: "${{ secrets.VAULT_NAMESPACE }}"
          method: jwt
          role: gha-vault-jwt
          path: gha
          #jwtGithubAudience: ${{ env.GITHUB_ACTION_REPOSITORY }}
          secrets: |
            secrets/data/gha test | VAULT_SECRET

      # - name: Print Secret
      #   run: echo $"{{ steps.secrets.outputs.VAULT_SECRET }}"


      # VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value')
      #     echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV