# .github/workflows/example.yml
name: Example
on:
  push:

jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
        - name: Import Secrets
          uses: grantorchard/vault-action@v2.3.2
          with:
            url: https://vault-cluster.vault.11eb56d6-0f95-3a99-a33c-0242ac110007.aws.hashicorp.cloud:8200
            method: github_jwt
            role: gha-vault-jwt
            path: gha
            secrets: |
                secrets/data/ci/aws accessKey | AWS_ACCESS_KEY_ID
            # ...


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - run: sleep 5 # there's still a race condition for now

#       - name: Get JWT Token
#         run: |
#           VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value')
#           echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV
#       - name: Authenticate to Vault
#         run: |
#           curl --request POST -H "X-Vault-Namespace: admin" --data "{ \"jwt\": \"${{ env.VAULT_JWT }}\", \"role\": \"gha-vault-jwt\"}" https://vault-cluster.vault.11eb56d6-0f95-3a99-a33c-0242ac110007.aws.hashicorp.cloud:8200/v1/auth/gha/login