# .github/workflows/example.yml
name: Vault Workflow
on:
  push:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve Vault Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: "${{ secrets.VAULT_ADDR }}"
          namespace: "${{ secrets.VAULT_NAMESPACE }}"
          method: jwt
          role: gha-vault-jwt
          path: gha
          #jwtGithubAudience: ${{ env.GITHUB_ACTION_REPOSITORY }}
          secrets: |
            secrets/gha test | VAULT_SECRET

      # - name: Print Secret
      #   run: echo $"{{ steps.secrets.outputs.VAULT_SECRET }}"